### PR TITLE
Add Ubuntu 22.04

### PR DESCRIPTION
**Pull request by Atry**

### CODE REVIEW

**Comment by Atry** [comment]
When build on Ubuntu 22.04:
```
bin/make-source-tarball && bin/make-package-in-throwaway-container ubuntu-22.04-jammy
```

The error message is:

```
Building CXX object CMakeFiles/cmTC_bae65.dir/src.cxx.o
/usr/bin/g++-10 -DIS_AARCH64  -g -O2 -ffile-prefix-map=/tmp/hhvmpkg.hhHlA2WC/hhvm-nightly-2022.04.13=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -o CMakeFiles/cmTC_bae65.dir/src.cxx.o -c /tmp/hhvmpkg.hhHlA2WC/hhvm-nightly-2022.04.13/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp/src.cxx
/tmp/hhvmpkg.hhHlA2WC/hhvm-nightly-2022.04.13/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp/src.cxx:3:2: error: #error Not ARMv8
    3 | #error Not ARMv8
      |  ^~~~~
gmake[3]: *** [CMakeFiles/cmTC_bae65.dir/build.make:78: CMakeFiles/cmTC_bae65.dir/src.cxx.o] Error 1
gmake[3]: Leaving directory '/tmp/hhvmpkg.hhHlA2WC/hhvm-nightly-2022.04.13/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp'
gmake[2]: *** [Makefile:127: cmTC_bae65/fast] Error 2
gmake[2]: Leaving directory '/tmp/hhvmpkg.hhHlA2WC/hhvm-nightly-2022.04.13/obj-x86_64-linux-gnu/CMakeFiles/CMakeTmp'
```

`-DIS_AARCH64` is suspicious. It should not not be present on an amd64 build.

**Comment by Atry** [comment]
I encountered a CMake error finding TBB, and created a PR to fix it in https://github.com/facebook/hhvm/pull/9069

**Comment by Atry** [comment]
The next error after applying https://github.com/facebook/hhvm/pull/9069:

```
-- Check size of off64_t
-- Check size of off64_t - done
-- Looking for unistd.h
-- Looking for unistd.h - found
-- OPENSSL_INCLUDE_DIR = /usr/include
-- OPENSSL_LIBRARY = /usr/lib/x86_64-linux-gnu/libssl.so
-- CRYPTO_LIBRARY = /usr/lib/x86_64-linux-gnu/libcrypto.so
-- OPENSSL_MAJOR_VERSION = 
-- OPENSSL_MINOR_VERSION = 
-- OPENSSL_FIX_VERSION = 
-- Looking for SHA512_DIGEST_LENGTH
-- Looking for SHA512_DIGEST_LENGTH - found
-- 
Cannot find appropriate system libraries for WITH_SSL=system.
Make sure you have specified a supported SSL version. 
Valid options are : 
system (use the OS openssl library), 
yes (synonym for system), 
</path/to/custom/openssl/installation>, 
wolfssl (use wolfSSL. See extra/README-wolfssl.txt on how to set this up)

CMake Error at cmake/ssl.cmake:68 (MESSAGE):
  Please install the appropriate openssl developer package.

Call Stack (most recent call first):
  cmake/ssl.cmake:409 (FATAL_SSL_NOT_FOUND_ERROR)
  CMakeLists.txt:1173 (MYSQL_CHECK_SSL)


-- Configuring incomplete, errors occurred!
See also "/tmp/hhvmpkg.bHdYQcob/hhvm-nightly-2022.04.13/obj-x86_64-linux-gnu/third-party/fb-mysql/bundled_fbmysqlclient-prefix/src/bundled_fbmysqlclient-build/CMakeFiles/CMakeOutput.log".
See also "/tmp/hhvmpkg.bHdYQcob/hhvm-nightly-2022.04.13/obj-x86_64-linux-gnu/third-party/fb-mysql/bundled_fbmysqlclient-prefix/src/bundled_fbmysqlclient-build/CMakeFiles/CMakeError.log".

```

**Comment by Atry** [comment]
Another error

```
In file included from /usr/include/tbb/concurrent_hash_map.h:17,
                 from /tmp/hhvmpkg.bHdYQcob/hhvm-nightly-2022.04.13/hphp/util/mutex.h:23,
                 from /tmp/hhvmpkg.bHdYQcob/hhvm-nightly-2022.04.13/hphp/util/lock.h:19,
                 from /tmp/hhvmpkg.bHdYQcob/hhvm-nightly-2022.04.13/hphp/runtime/vm/instance-bits.h:24,
                 from /tmp/hhvmpkg.bHdYQcob/hhvm-nightly-2022.04.13/hphp/runtime/vm/class.h:31,
                 from /tmp/hhvmpkg.bHdYQcob/hhvm-nightly-2022.04.13/hphp/runtime/base/object-data.h:27,
                 from /tmp/hhvmpkg.bHdYQcob/hhvm-nightly-2022.04.13/hphp/runtime/base/type-object.h:19,
                 from /tmp/hhvmpkg.bHdYQcob/hhvm-nightly-2022.04.13/hphp/runtime/base/tv-conversions.h:23,
                 from /tmp/hhvmpkg.bHdYQcob/hhvm-nightly-2022.04.13/hphp/runtime/base/type-variant.h:20,
                 from /tmp/hhvmpkg.bHdYQcob/hhvm-nightly-2022.04.13/hphp/runtime/base/array-data-defs.h:23,
                 from /tmp/hhvmpkg.bHdYQcob/hhvm-nightly-2022.04.13/hphp/runtime/base/array-init.h:21,
                 from /tmp/hhvmpkg.bHdYQcob/hhvm-nightly-2022.04.13/hphp/system/systemlib.cpp:19:
/usr/include/tbb/../oneapi/tbb/concurrent_hash_map.h: In instantiation of 'class tbb::detail::d2::concurrent_hash_map<const HPHP::StringData*, int, HPHP::StringDataHashCompare, HPHP::WrapAllocator<HPHP::vm_malloc, HPHP::vm_sized_free, char> >':
/tmp/hhvmpkg.bHdYQcob/hhvm-nightly-2022.04.13/hphp/runtime/vm/litstr-table.h:140:13:   required from here
/usr/include/tbb/../oneapi/tbb/concurrent_hash_map.h:625:77: error: static assertion failed: value_type of the container must be the same as its allocator's
  625 |     static_assert(std::is_same<value_type, typename Allocator::value_type>::value,
      |                                                                             ^~~~~
/usr/include/tbb/../oneapi/tbb/concurrent_hash_map.h: In instantiation of 'tbb::detail::d2::concurrent_hash_map<Key, T, HashCompare, Allocator>::allocator_type tbb::detail::d2::concurrent_hash_map<Key, T, HashCompare, Allocator>::get_allocator() const [with Key = const HPHP::StringData*; T = int; HashCompare = HPHP::StringDataHashCompare; Allocator = HPHP::WrapAllocator<HPHP::vm_malloc, HPHP::vm_sized_free, char>; tbb::detail::d2::concurrent_hash_map<Key, T, HashCompare, Allocator>::allocator_type = HPHP::WrapAllocator<HPHP::vm_malloc, HPHP::vm_sized_free, char>]':
/usr/include/tbb/../oneapi/tbb/concurrent_hash_map.h:653:50:   required from 'void tbb::detail::d2::concurrent_hash_map<Key, T, HashCompare, Allocator>::delete_node(tbb::detail::d2::concurrent_hash_map<Key, T, HashCompare, Allocator>::node_base*) [with Key = const HPHP::StringData*; T = int; HashCompare = HPHP::StringDataHashCompare; Allocator = HPHP::WrapAllocator<HPHP::vm_malloc, HPHP::vm_sized_free, char>; tbb::detail::d2::concurrent_hash_map<Key, T, HashCompare, Allocator>::node_base = tbb::detail::d2::hash_map_node_base<tbb::detail::d1::spin_rw_mutex>]'
/usr/include/tbb/../oneapi/tbb/concurrent_hash_map.h:1021:21:   required from 'void tbb::detail::d2::concurrent_hash_map<Key, T, HashCompare, Allocator>::clear() [with Key = const HPHP::StringData*; T = int; HashCompare = HPHP::StringDataHashCompare; Allocator = HPHP::WrapAllocator<HPHP::vm_malloc, HPHP::vm_sized_free, char>]'
/usr/include/tbb/../oneapi/tbb/concurrent_hash_map.h:1029:30:   required from 'tbb::detail::d2::concurrent_hash_map<Key, T, HashCompare, Allocator>::~concurrent_hash_map() [with Key = const HPHP::StringData*; T = int; HashCompare = HPHP::StringDataHashCompare; Allocator = HPHP::WrapAllocator<HPHP::vm_malloc, HPHP::vm_sized_free, char>]'
/tmp/hhvmpkg.bHdYQcob/hhvm-nightly-2022.04.13/hphp/runtime/vm/litstr-table.h:123:17:   required from here
/usr/include/tbb/../oneapi/tbb/concurrent_hash_map.h:1082:76: error: could not convert '((const tbb::detail::d2::concurrent_hash_map<const HPHP::StringData*, int, HPHP::StringDataHashCompare, HPHP::WrapAllocator<HPHP::vm_malloc, HPHP::vm_sized_free, char> >*)this)->tbb::detail::d2::concurrent_hash_map<const HPHP::StringData*, int, HPHP::StringDataHashCompare, HPHP::WrapAllocator<HPHP::vm_malloc, HPHP::vm_sized_free, char> >::<anonymous>.tbb::detail::d2::hash_map_base<HPHP::WrapAllocator<HPHP::vm_malloc, HPHP::vm_sized_free, char>, tbb::detail::d1::spin_rw_mutex>::get_allocator()' from 'WrapAllocator<HPHP::vm_malloc,HPHP::vm_sized_free,tbb::detail::d2::hash_map_base<HPHP::WrapAllocator<HPHP::vm_malloc, HPHP::vm_sized_free, char>, tbb::detail::d1::spin_rw_mutex>::bucket>' to 'WrapAllocator<HPHP::vm_malloc,HPHP::vm_sized_free,char>'
 1082 |     allocator_type get_allocator() const { return base_type::get_allocator(); }
      |                                                                            ^
      |                                                                            |
      |                                                                            WrapAllocator<HPHP::vm_malloc,HPHP::vm_sized_free,tbb::detail::d2::hash_map_base<HPHP::WrapAllocator<HPHP::vm_malloc, HPHP::vm_sized_free, char>, tbb::detail::d1::spin_rw_mutex>::bucket>
/usr/include/tbb/../oneapi/tbb/concurrent_hash_map.h: In instantiation of 'tbb::detail::d2::concurrent_hash_map<Key, T, HashCompare, Allocator>::pointer tbb::detail::d2::concurrent_hash_map<Key, T, HashCompare, Allocator>::node::storage() [with Key = const HPHP::StringData*; T = int; HashCompare = HPHP::StringDataHashCompare; Allocator = HPHP::WrapAllocator<HPHP::vm_malloc, HPHP::vm_sized_free, char>; tbb::detail::d2::concurrent_hash_map<Key, T, HashCompare, Allocator>::pointer = char*]':
/usr/include/tbb/../oneapi/tbb/concurrent_hash_map.h:654:86:   required from 'void tbb::detail::d2::concurrent_hash_map<Key, T, HashCompare, Allocator>::delete_node(tbb::detail::d2::concurrent_hash_map<Key, T, HashCompare, Allocator>::node_base*) [with Key = const HPHP::StringData*; T = int; HashCompare = HPHP::StringDataHashCompare; Allocator = HPHP::WrapAllocator<HPHP::vm_malloc, HPHP::vm_sized_free, char>; tbb::detail::d2::concurrent_hash_map<Key, T, HashCompare, Allocator>::node_base = tbb::detail::d2::hash_map_node_base<tbb::detail::d1::spin_rw_mutex>]'
/usr/include/tbb/../oneapi/tbb/concurrent_hash_map.h:1021:21:   required from 'void tbb::detail::d2::concurrent_hash_map<Key, T, HashCompare, Allocator>::clear() [with Key = const HPHP::StringData*; T = int; HashCompare = HPHP::StringDataHashCompare; Allocator = HPHP::WrapAllocator<HPHP::vm_malloc, HPHP::vm_sized_free, char>]'
/usr/include/tbb/../oneapi/tbb/concurrent_hash_map.h:1029:30:   required from 'tbb::detail::d2::concurrent_hash_map<Key, T, HashCompare, Allocator>::~concurrent_hash_map() [with Key = const HPHP::StringData*; T = int; HashCompare = HPHP::StringDataHashCompare; Allocator = HPHP::WrapAllocator<HPHP::vm_malloc, HPHP::vm_sized_free, char>]'
/tmp/hhvmpkg.bHdYQcob/hhvm-nightly-2022.04.13/hphp/runtime/vm/litstr-table.h:123:17:   required from here
/usr/include/tbb/../oneapi/tbb/concurrent_hash_map.h:644:37: error: cannot convert 'tbb::detail::d2::concurrent_hash_map<const HPHP::StringData*, int, HPHP::StringDataHashCompare, HPHP::WrapAllocator<HPHP::vm_malloc, HPHP::vm_sized_free, char> >::value_type*' {aka 'std::pair<const HPHP::StringData* const, int>*'} to 'tbb::detail::d2::concurrent_hash_map<const HPHP::StringData*, int, HPHP::StringDataHashCompare, HPHP::WrapAllocator<HPHP::vm_malloc, HPHP::vm_sized_free, char> >::pointer' {aka 'char*'} in return
  644 |         pointer storage() { return &my_value; }
      |                                     ^~~~~~~~
      |                                     |
      |                                     tbb::detail::d2::concurrent_hash_map<const HPHP::StringData*, int, HPHP::StringDataHashCompare, HPHP::WrapAllocator<HPHP::vm_malloc, HPHP::vm_sized_free, char> >::value_type* {aka std::pair<const HPHP::StringData* const, int>*}
```

It is also related with TBB

**Comment by mamchyts** [comment]
Hi, any updates?

PS. ```E: The repository 'https://dl.hhvm.com/ubuntu jammy Release' does not have a Release file.```

**Comment by Atry** [comment]
You can try the experimental Nix package on any Linux distribution, including Ubuntu 22.04

https://hhvm.com/blog/2022/07/12/experimenting-with-nix-github-actions-and-visual-studio-code.html
